// Generated by https://quicktype.io

export interface CharacterByIDResponse {
  data: DataCharacterById;
}

export interface DataCharacterById {
  charactersByIds: CharactersByID[];
}

export interface CharactersByID {
  id:    string;
  name:  string;
  image: string;
}
