// Generated by https://quicktype.io

export interface CharacterResponse {
  data: DataCharacter;
}

export interface DataCharacter {
  character: Character;
}

export interface Character {
  name:     string;
  id:       string;
  image:    string;
  status:   string;
  episode:  Episode[];
  created:  string;
  location: Location;
}

export interface Episode {
  id:   string;
  name: string;
}

export interface Location {
  name: string;
}
