// Generated by https://quicktype.io

export interface PagesResponse {
  data: DataPages;
}

export interface DataPages {
  characters: Characters;
}

export interface Characters {
  info: Info;
}

export interface Info {
  pages: number;
}
